### ISSUE TITLE
Unable to create invoice with tax

### ISSUE THREAD

**Issue by Saphar** [OCA/l10n-germany#36]
I installed this plugin from the Apps menu and I tried to create an invoice with different taxes, but I got this error message:
> Account Erlöse 19% USt does not authorize to have tax 7% Umsatzsteuer specified on the line. Change the tax used in this invoice or remove all taxes from the account

After uninstalling the module I was able to create invoices with taxes. I couldn't find where this error comes from.
I am using Odoo v12.

**Comment by pedrobaeza** [comment]
Which module?

**Comment by Saphar** [comment]
If you go to Apps and install Germany - Accounting. Is it a different module than this one?

**Comment by pedrobaeza** [comment]
Yes, that's not something of this repository.

**Comment by Etherflash** [comment]
I had a similar problem, for an EU costumer with no TAX ID. Odoo wouldn't allow me to add tax to the products: giving me the not helpfull error message: "Account Steuerfreie EG-Lieferungen §4, 1b UStG does not authorize to have tax 19% Umsatzsteuer specified on the line.        Change the tax used in this invoice or remove all taxes from the account" To fix the issue I had to click on the taxes (but not in eddit mode) than in the popup click on the Steuerfreie EG-Lieferungen -> Edit -> add the proper tax line and it works. Now you just have to be carefull because you can send an invoice with taxes to custumers which should receive an invoice with taxes. This was written for Odoo 13

**Comment by DarkSorcy** [comment]
> I had a similar problem, for an EU costumer with no TAX ID. Odoo wouldn't allow me to add tax to the products: giving me the not helpfull error message: "Account Steuerfreie EG-Lieferungen §4, 1b UStG does not authorize to have tax 19% Umsatzsteuer specified on the line. Change the tax used in this invoice or remove all taxes from the account" To fix the issue I had to click on the taxes (but not in eddit mode) than in the popup click on the Steuerfreie EG-Lieferungen -> Edit -> add the proper tax line and it works. Now you just have to be carefull because you can send an invoice with taxes to custumers which should receive an invoice with taxes. This was written for Odoo 13

solves the issue on my side. Thanks for this suggestion.
